This is cutadapt 4.5 with Python 3.10.13
Command line parameters: -m 20 -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCA -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT -o out/cutadapt/ERR2868174_1.trimmed.fastq.gz -p out/cutadapt/ERR2868174_2.trimmed.fastq.gz data/ERR2868174_1.fastq.gz data/ERR2868174_2.fastq.gz
Processing paired-end reads on 1 core ...
ERROR: [Errno 2] No such file or directory: 'data/ERR2868174_1.fastq.gz'
